gnome-panel: Fix compilation against gnome-desktop 3.8+ 0001-panel-Fix-launcher-icon-animation-ending-with-black.patch, 0002-fix-build-error-due-to-missing-gweather-xml.h.patch, 0003-na-apply-style-after-realize.patch, 0004-drop-support-for-commandline-based-calendar-tasks-ap.patch, 0005-panel-run-dialog-resurrect-function-gnome_desktop_pr.patch, 0006-panel-run-dialog-rename-helper-function.patch, 0007-notification_area-Use-the-generic-marshaller.patch: Added from http://git.pld-linux.org/gitweb.cgi/packages/gnome-panel.git/commitdiff/fd33e2e0d0dd96ab56e3ee8b297e7de83556c0e0
See https://bugzilla.gnome.org/show_bug.cgi?id=692385 for
removal of gnome-desktop-utils.h which lead me down this chase.

panel-run-dialog.c:45:50: fatal error:
libgnome-desktop/gnome-desktop-utils.h: No such file or directory
compilation terminated.