xf86-video-wsfb: Updated to 0.3.0 SOURCE matches upstream posted MD5
Fails to compile:
wsfb_driver.c:48:33: error: dev/wscons/wsconsio.h: No such file or
directory