kdepimlibs4: Updated to 4.5.2, now compiles with libical 1.46
Seems to work with the rest of KDE4 at 4.5.1, but I will work on
updating those as well.

Linking CXX shared library ../lib/libkpimutils.so
[ 18%] Built target kpimutils
[ 18%] Building CXX object kcal/CMakeFiles/kcal.dir/icalformat_p.o
/usr/src/kdepimlibs-4.5.1/kcal/icalformat_p.cpp: In member function
'icalproperty*
KCal::ICalFormatImpl::writeAttachment(KCal::Attachment*)':
/usr/src/kdepimlibs-4.5.1/kcal/icalformat_p.cpp:787: error: invalid
conversion from 'unsigned char*' to 'const char*'
/usr/src/kdepimlibs-4.5.1/kcal/icalformat_p.cpp:787: error:
initializing argument 1 of 'icalattach* icalattach_new_from_data(const
char*, void (*)(unsigned char*, void*), void*)'
make[2]: *** [kcal/CMakeFiles/kcal.dir/icalformat_p.o] Error 1