grub2: Fix compilation with glibc 2.16+ gets removed from GNU libc, see http://permalink.gmane.org/gmane.comp.lib.gnulib.bugs/30292)
make[4]: Entering directory `/usr/src/grub-2.00/grub-core/gnulib'
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../intl   -march=native
-mtune=native -m32 -pipe   -Os -MT argp-eexst.o -MD -MP -MF
.deps/argp-eexst.Tpo -c -o argp-eexst.o argp-eexst.c
In file included from argp.h:22:0,
                 from argp-eexst.c:25:
./stdio.h:456:20: error: 'gets' undeclared here (not in a function)