gnome-settings-daemon: Updated to 3.6.1 SOURCE matches upstream posted SHA256
Making all in print-notifications
make[3]: Entering directory
`/usr/src/gnome-settings-daemon-3.4.2/plugins/print-notifications'
  CC     libprint_notifications_la-gsd-print-notifications-manager.lo
gsd-print-notifications-manager.c: In function 'on_cups_notification':
gsd-print-notifications-manager.c:399:45: error: dereferencing pointer
to incomplete type
gsd-print-notifications-manager.c:402:60: error: dereferencing pointer
to incomplete type
gsd-print-notifications-manager.c:696:65: warning:
'ppdLocalizeIPPReason' is deprecated (declared at
/usr/include/cups/ppd.h:438) [-Wdeprecated-declarations]
gsd-print-notifications-manager.c: In function 'renew_subscription':
gsd-print-notifications-manager.c:892:64: error: dereferencing pointer
to incomplete type
gsd-print-notifications-manager.c:897:78: error: dereferencing pointer
to incomplete type
make[3]: ***
[libprint_notifications_la-gsd-print-notifications-manager.lo] Error 1
make[3]: Leaving directory
`/usr/src/gnome-settings-daemon-3.4.2/plugins/print-notifications'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory
`/usr/src/gnome-settings-daemon-3.4.2/plugins'