Revert "linux 3.7.2"
This reverts commit 809e0252be8277013382bbc258e4b2ff7017812a.

/usr/src/linux/include/linux/socket.h:111:32: error: conflicting types
for '__cmsg_nxthdr'
/usr/include/bits/socket.h:286:1: note: previous definition of
'__cmsg_nxthdr' was here
In file included from /usr/src/linux/include/linux/kernel.h:6:0,