Revert "disk/e2fsprogs: version 1.44.0"
This reverts commit 8958132d3560c21e9cfca72ee32bfe26eb139592.

Breaks current, and latest, btrfs-progs: See https://bugzilla.kernel.org/show_bug.cgi?id=199071
convert/source-ext2.c: In function ‘ext2_xattr_check_entry’:
convert/source-ext2.c:425:13: error: ‘struct ext2_ext_attr_entry’ has no member named ‘e_value_block’; did you mean ‘e_value_offs’?
  if (entry->e_value_block != 0 || value_size > size ||
             ^~~~~~~~~~~~~
             e_value_offs
make: *** [Makefile:282: convert/source-ext2.o] Error 1