telepathy-glib: 0.13.x requires vala 0.11.3+ (devel)
$ gaze version vala telepathy-glib
Grimoire  Section    Spell           Grimoire Version  Installed Version
--------  -------    -----           ----------------  -----------------
test      devel      vala            0.10.4            0.10.4
test      telephony  telepathy-glib  0.14.3            0.12.6

Making all in vala
make[2]: Entering directory `/usr/src/telepathy-glib-0.14.3/vala'
/usr/bin/vapigen \
        --library telepathy-glib \
        --pkg gio-2.0 \
        ../telepathy-glib/TelepathyGLib-0.12.gir \

error: The type name `GLib.TypeInterface' could not be found
Generation failed: 1 error(s), 0 warning(s)
make[2]: *** [telepathy-glib.vapi] Error 1
make[2]: Leaving directory `/usr/src/telepathy-glib-0.14.3/vala'
make[1]: Leaving directory `/usr/src/telepathy-glib-0.14.3'
make[1]: *** [all-recursive] Error 1