mythes: Depends on hunspell
example.cxx:7:33: error: hunspell/hunspell.hxx: No such file or
directory
(cherry picked from commit feda4892ab302ea0ae9a289b7f92243349f5d612)