nmap: Remove libdnet, add option for nc symlink, update CONFLICTS
Remove libdnet, the latest (from 2005) version is not compatible with this version of nmap.
      nmap.cc:166:45: fatal error: libdnet-stripped/include/config.h: No such file or directory
Add option for nc -> ncat symlink
Conflict with nc/netcat (even if `nc` symlink option is not selected)