grub2: Disable PIC for x86
Error without PIC disabled on x86:
gcc -DHAVE_CONFIG_H -I. -I..  -Wall -W -I../include -I../include
-DGRUB_MACHINE_PCBIOS=1 -DGRUB_MACHINE=I386_PC -nostdinc -isystem
/usr/lib/gcc/i686-pc-linux-gnu/4.6.2/include
-DGRUB_FILE=\"loader/i386/xnu.c\" -I. -I. -I.. -I.. -I../include
-I../include     -Os -Wall -W -Wshadow -Wpointer-arith
-Wmissing-prototypes -Wundef -Wstrict-prototypes -g -falign-jumps=1
-falign-loops=1 -falign-functions=1 -mno-mmx -mno-sse -mno-sse2
-mno-3dnow -fno-dwarf2-cfi-asm -m32 -fno-stack-protector
-mno-stack-arg-probe -Wno-trampolines   -mrtd -mregparm=3
-ffreestanding  -march=native -mtune=native -m32 -pipe -DPIC -fPIC -O2
-MT loader/i386/xnu_module-xnu.o -MD -MP -MF
loader/i386/.deps-core/xnu_module-xnu.Tpo -c -o
loader/i386/xnu_module-xnu.o `test -f 'loader/i386/xnu.c' || echo
'./'`loader/i386/xnu.c
loader/i386/xnu.c: In function 'grub_cpu_xnu_fill_devicetree':
loader/i386/xnu.c:184:3: error: PIC register clobbered by '%rbx' in
'asm'
In file included from loader/i386/xnu.c:27:0:
../include/grub/i386/tsc.h:47:3: error: PIC register clobbered by '%rbx'
in 'asm'
../include/grub/i386/tsc.h:47:3: error: PIC register clobbered by '%rbx'
in 'asm'
make[3]: *** [loader/i386/xnu_module-xnu.o] Error 1
make[3]: Leaving directory `/usr/src/grub-1.99/grub-core'
(cherry picked from commit 956770cf4398d4bf92115606a191454993e5493f)