libvirt: Updated to 0.10.2, depends on yajl
Fixes compilation with glibc 2.16+:
make[4]: Entering directory `/usr/src/libvirt-0.9.9/gnulib/lib'
  CC     md5.lo
In file included from md5.h:26:0,
                 from md5.c:27:
./stdio.h:1032:20: error: 'gets' undeclared here (not in a function)
make[4]: *** [md5.lo] Error 1