Revert "util-linux: No longer depends on e2fsprogs for blkid"
This reverts commit 3396ebff9d9ad7bf0ea7b6f985edfcdb18f7f268.

But if e2fsprogs isn't installed when util-linux is cast, we get:
read.c:28:23: error: uuid/uuid.h: No such file or directory