Revert "devel/nodejs: version 16.6.2"
This reverts commit 3d2ac23f3baa89db53034b42999c9b7472eaa991.

../src/cares_wrap.h:25:11: fatal error: 'ares_nameser.h' file not found?