lightdm: Remove MOC files (need to be regenerated with qt 4.8)
The old MOC files were generated using qt 4.7, which gives the following
error when used with qt 4.8 headers:
greeter_moc.cpp:14:2: error: #error "This file was generated using the
moc from 4.7.4. It"
greeter_moc.cpp:15:2: error: #error "cannot be used with the include
files from this version of Qt."
greeter_moc.cpp:16:2: error: #error "(The moc has changed too much.)"