mysql: Add -fpermissive in CXXFLAGS with 5.1.67 (!$OLD) Add -fpermissive in CXXFLAGS with 5.1.67 (!$OLD) for extra/yassl/taocrypt/src/Makefile.in
$ cast mysql
...
Making all in src
make[5]: Entering directory
`/usr/src/mysql-5.1.67/extra/yassl/taocrypt/src' /bin/sh ../../../../libtool --preserve-dup-deps --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../../../include -I./../include -I./../mySTL  -D_GNU_SOURCE -DYASSL_PURE_C -DYASSL_THREAD_SAFE -march=native -mtune=native -m32 -pipe -DPIC -fPIC -O2   -fno-implicit-templates -fno-exceptions -fno-rtti -MT libtaocrypt_la-integer.lo -MD -MP -MF .deps/libtaocrypt_la-integer.Tpo -c -o libtaocrypt_la-integer.lo `test -f 'integer.cpp' || echo './'`integer.cpp libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../../../include -I./../include -I./../mySTL -D_GNU_SOURCE -DYASSL_PURE_C -DYASSL_THREAD_SAFE -march=native -mtune=native -m32 -pipe -DPIC -fPIC -O2 -fno-implicit-templates -fno-exceptions -fno-rtti -MT libtaocrypt_la-integer.lo -MD -MP -MF .deps/libtaocrypt_la-integer.Tpo -c integer.cpp  -fPIC -DPIC -o .libs/libtaocrypt_la-integer.o
integer.cpp: In member function 'TaoCrypt::AlignedAllocator<T>::pointer TaoCrypt::AlignedAllocator<T>::allocate(TaoCrypt::AlignedAllocator<T>::size_type, const void*)':
integer.cpp:76:22: error: there are no arguments to 'max_size' that depend on a template parameter, so a declaration of 'max_size' must be available [-fpermissive]
integer.cpp:76:22: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
make[5]: *** [libtaocrypt_la-integer.lo] Error 1
make[5]: Leaving directory
`/usr/src/mysql-5.1.67/extra/yassl/taocrypt/src'
(cherry picked from commit 8d0713e6ef5dee3f070d62d8d18f74124b0fc4e0)