lvm: LIBS hack for pthread and uuid is still required
Without this patch:
gcc -march=core2 -fPIC -DPIC -pipe -DPIC -fPIC -O2 -s -Wl,-O1 -Wl,--hash-style=gnu -L./libdm -L./lib -L./libdaemon/client -L./daemons/dmeventd -L../libdm -L../lib -L../libdaemon/client -L../daemons/dmeventd -static -L../libdm/ioctl -o lvm.static \ dumpconfig.o formats.o lvchange.o lvconvert.o lvconvert_poll.o lvcreate.o lvdisplay.o lvextend.o lvmchange.o lvmcmdline.o lvmdiskscan.o lvreduce.o lvremove.o lvrename.o lvresize.o lvscan.o polldaemon.o pvchange.o pvck.o pvcreate.o pvdisplay.o pvmove.o pvmove_poll.o pvremove.o pvresize.o pvscan.o reporter.o segtypes.o tags.o toollib.o vgcfgbackup.o vgcfgrestore.o vgchange.o vgck.o vgcreate.o vgconvert.o vgdisplay.o vgexport.o vgextend.o vgimport.o vgmerge.o vgmknodes.o lvpoll.o vgreduce.o vgremove.o vgrename.o vgscan.o vgsplit.o lvm-static.o -llvm-internal -ldaemonclient  -ldl -lblkid -ldevmapper-event -ldevmapper   -lblkid -lrt
../lib/liblvm-internal.a(sharedlib.o): In function
`load_shared_library': sharedlib.c:(.text+0x130): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../lib/libblkid.a(libblkid_la-probe.o):
In function `blkid_unparse_uuid': probe.c:(.text+0x1e81): undefined reference to `uuid_unparse'
../daemons/dmeventd/libdevmapper-event.a(libdevmapper-event.o): In function `dm_event_log':
libdevmapper-event.c:(.text+0x2cf7): undefined reference to `pthread_mutex_lock'
libdevmapper-event.c:(.text+0x2e29): undefined reference to `pthread_self'
libdevmapper-event.c:(.text+0x2d2f): undefined reference to `pthread_mutex_unlock'
../libdm/ioctl/libdevmapper.a(pool.o): In function `dm_pool_create':
pool.c:(.text+0x134): undefined reference to `pthread_mutex_lock'
pool.c:(.text+0x14f): undefined reference to `pthread_mutex_unlock'
../libdm/ioctl/libdevmapper.a(pool.o): In function `dm_pool_destroy':
pool.c:(.text+0x209): undefined reference to `pthread_mutex_lock'
pool.c:(.text+0x21d): undefined reference to `pthread_mutex_unlock'
../libdm/ioctl/libdevmapper.a(pool.o): In function `dm_pools_check_leaks':
pool.c:(.text+0x6be): undefined reference to `pthread_mutex_lock'
pool.c:(.text+0x7a9): undefined reference to `pthread_mutex_unlock'
pool.c:(.text+0x82e): undefined reference to `pthread_mutex_unlock'
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `__gthread_mutex_lock':
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:748: undefined reference to `pthread_mutex_lock'
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:748: undefined reference to `pthread_mutex_lock'
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:748: undefined reference to `pthread_mutex_lock'
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:748: undefined reference to `pthread_mutex_lock'
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `__gthread_mutex_unlock':
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:778: undefined reference to `pthread_mutex_unlock'
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `__gthread_mutex_lock':
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:748: undefined reference to `pthread_mutex_lock'
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `__gthread_mutex_unlock':
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:778: undefined reference to `pthread_mutex_unlock'
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:778: undefined reference to `pthread_mutex_unlock'
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:778: undefined reference to `pthread_mutex_unlock'
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:778: undefined reference to `pthread_mutex_unlock'
/usr/src/gcc-5.3.0.bld/x86_64-pc-linux-gnu/libgcc/./gthr-default.h:778: undefined reference to `pthread_mutex_unlock'
collect2: error: ld returned 1 exit status
Makefile:149: recipe for target 'lvm.static' failed