btrfs-progs: Depends on babel, python-sphinx, python-sphinxcontrib-applehelp,
python-sphinxcontrib-devhelp, and python-sphinxcontrib-qthelp for documentation

Also depends on python-sphinxcontrib-htmlhelp and python-sphinxcontrib-serializinghtml
See https://github.com/sphinx-doc/sphinx/issues/9434

Still fails with "AttributeError: 'document' object has no attribute 'findall'"
Not building documentation works for now