nip2: Updated to 7.30.1 Apply yyleng.patch to fix compilation with newer bison/flex Fixes for 7.26.x as well
gcc -DHAVE_CONFIG_H -I. -I.. -pthread -fopenmp -I/usr/include/glib-2.0
-I/usr/lib/glib-2.0/include -I/usr/include/gtk-2.0
-I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo
-I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0
-I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12
-I/usr/include/libdrm -I/usr/include/libxml2 -I/usr/include/ImageMagick
-I/usr/include/orc-0.4 -I/usr/include/OpenEXR    -DG_DISABLE_ASSERT
-DG_DISABLE_CHECKS      -march=native -mtune=native -m32 -pipe -DPIC
-fPIC -O2 -MT nip2-lex.o -MD -MP -MF .deps/nip2-lex.Tpo -c -o nip2-lex.o
`test -f 'lex.c' || echo './'`lex.c
In file included from ip.h:488:0,
                 from lex.l:31:
parser.h:58:12: error: conflicting types for 'yyleng'
lex.c:275:11: note: previous declaration of 'yyleng' was here
make[3]: *** [nip2-lex.o] Error 1