gnome-panel: Depends on gnome-desktop in addition to gnome-desktop3
With gnome-desktop3 installed, but not gnome-desktop:
panel-run-dialog.c:45:50: fatal error:
libgnome-desktop/gnome-desktop-utils.h: No such file or directory