qemu: nss dependency moved to libcacard in 2.6.0
I based this on smartcard being related to nss in prior versions.

ERROR: unknown option --enable-smartcard-nss