mesademos: Disable building egl
Making all in opengl
make[3]: Entering directory `/usr/src/mesa-demos-8.0.1/src/egl/opengl'
  CCLD   xeglgears
xeglgears.o: In function `.L153':
xeglgears.c:(.text+0x2474): undefined reference to
`glEGLImageTargetTexture2DOES'
collect2: ld returned 1 exit status
make[3]: *** [xeglgears] Error 1
(cherry picked from commit 09c9e98c6d7e2610c4f3fd14c2241e731f2b1d9e)