linux-pam: Updated to 1.1.6 Upstream MD5/SHA1 not posted for 1.1.6
Fixes compilation with glibc 2.16+:
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../..
-I../../libpam/include -I../.
./libpamc/include -DCHKPWD_HELPER=\"/lib/security/unix_chkpwd\"
-DUPDATE_HELPER=
\"/lib/security/unix_update\" -march=native -mtune=native -m32 -pipe
-DPIC -fPIC
 -O2 -MT pam_unix_acct.lo -MD -MP -MF .deps/pam_unix_acct.Tpo -c
pam_unix_acct.c
  -fPIC -DPIC -o .libs/pam_unix_acct.o
pam_unix_acct.c: In function '_unix_run_verify_binary':
pam_unix_acct.c:97:19: error: storage size of 'rlim' isn't known
pam_unix_acct.c:106:19: error: 'RLIMIT_NOFILE' undeclared (first use in
this function)
pam_unix_acct.c:106:19: note: each undeclared identifier is reported
only once for each function it appears in
make[3]: *** [pam_unix_acct.lo] Error 1
make[3]: Leaving directory `/usr/src/Linux-PAM-1.1.5/modules/pam_unix'