Revert "evolution-exchange: Updated to 3.5.2"
This reverts commit ac31669e0bd22df6df21b79193ea71f681ce77a9.

Building e2k-propnames.c
/usr/bin/make  all-am
make[4]: Entering directory
`/usr/src/evolution-exchange-3.5.2/server/lib'
  CC     libexchange_la-e2k-enumtypes.lo
  CC     libexchange_la-e2k-marshal.lo
  CC     libexchange_la-camel-exchange-settings.lo
  CC     libexchange_la-e2k-action.lo
  CC     libexchange_la-e2k-autoconfig.lo
In file included from e2k-autoconfig.c:66:0:
/usr/include/evolution-data-server-3.6/libedataserver/e-data-server-util.h:23:2:
error: #error "Only <libedataserver/libedataserver.h> should be included
directly."
In file included from e2k-autoconfig.c:67:0:
/usr/include/evolution-data-server-3.6/libedataserver/e-url.h:29:2:
error: #error "Only <libedataserver/libedataserver.h> should be included
directly."
In file included from e2k-autoconfig.c:68:0:
/usr/include/evolution-data-server-3.6/libedataserverui/e-passwords.h:24:2:
error: #error "Only <libedataserverui/libedataserverui.h> should be
included directly."
make[4]: *** [libexchange_la-e2k-autoconfig.lo] Error 1
make[4]: Leaving directory
`/usr/src/evolution-exchange-3.5.2/server/lib'