guile: Updated to 2.0.6
Fixes compilation with glibc 2.16+
make[4]: Entering directory `/usr/src/guile-2.0.5/lib'
  CC     localcharset.lo
In file included from localcharset.c:28:0:
./stdio.h:1030:20: error: 'gets' undeclared here (not in a function)
make[4]: *** [localcharset.lo] Error 1