evolution: Updated to 3.6.1 mono, rarian, python, and gnome-pilot-conduits are no longer used --disable-contacts-map is not available (default=no) --disable-nm no longer exists
Fixes evolution-data-server/evolution 3.4.1:
Making all in caldav
make[4]: Entering directory
`/usr/src/evolution-data-server-3.4.1/calendar/backends/caldav'
  CC     libecalbackendcaldav_la-e-cal-backend-caldav-factory.lo
  CC     libecalbackendcaldav_la-e-cal-backend-caldav.lo
e-cal-backend-caldav.c: In function 'check_calendar_changed_on_server':
e-cal-backend-caldav.c:1191:28: error: dereferencing pointer to
incomplete type
e-cal-backend-caldav.c:1192:18: error: dereferencing pointer to
incomplete type
e-cal-backend-caldav.c: In function 'caldav_server_list_objects':
e-cal-backend-caldav.c:1339:28: error: dereferencing pointer to
incomplete type
e-cal-backend-caldav.c:1340:18: error: dereferencing pointer to
incomplete type
e-cal-backend-caldav.c: In function
'caldav_receive_schedule_outbox_url':
e-cal-backend-caldav.c:1784:28: error: dereferencing pointer to
incomplete type
e-cal-backend-caldav.c:1785:18: error: dereferencing pointer to
incomplete type
e-cal-backend-caldav.c:1834:28: error: dereferencing pointer to
incomplete type
e-cal-backend-caldav.c:1835:18: error: dereferencing pointer to
incomplete type
make[4]: *** [libecalbackendcaldav_la-e-cal-backend-caldav.lo] Error 1
make[4]: Leaving directory
`/usr/src/evolution-data-server-3.4.1/calendar/backends/caldav'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory
`/usr/src/evolution-data-server-3.4.1/calendar/backends'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory
`/usr/src/evolution-data-server-3.4.1/calendar'
make[1]: Leaving directory `/usr/src/evolution-data-server-3.4.1'
make[1]: *** [all-recursive] Error 1