Revert "xorg-server: Updated to 1.6.5"
This reverts commit e8e77d63ad8e16c4b16590657b7880a28821cd48.

Fails same as 1.6.4, even with all the merges from devel-xorg-modular:
/usr/bin/make  all-am
make[2]: Entering directory `/usr/src/xorg-server-1.6.5/dix'
../doltcompile gcc -DHAVE_CONFIG_H -I. -I../include
-DHAVE_DIX_CONFIG_H -Wall -Wpointer-arith -Wstrict-prototypes
-Wmissing-prototypes -Wmissing-declarations -Wnested-externs
-fno-strict-aliasing -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT
-DDBUS_API_SUBJECT_TO_CHANGE -I/usr/include/freetype2
-I/usr/include/pixman-1 -I/usr/include/hal -I/usr/include/dbus-1.0
-I/usr/lib/dbus-1.0/include    -I../include -I../include -I../Xext
-I../composite -I../damageext -I../xfixes -I../Xi -I../mi
-I../miext/shadow  -I../miext/damage -I../render -I../randr -I../fb
-DVENDOR_NAME=\""The X.Org Foundation"\" -DVENDOR_RELEASE="(((1) *
10000000) + ((6) * 100000) + ((5) * 1000) + 0)" -march=core2 -m32 -pipe
-DPIC -fPIC -O2 -MT dispatch.lo -MD -MP -MF .deps/dispatch.Tpo -c -o
dispatch.lo dispatch.c
In file included from ../Xext/panoramiX.h:45,
                 from dispatch.c:135:
/usr/include/X11/extensions/panoramiXext.h:49: error: expected ')'
before '*' token
/usr/include/X11/extensions/panoramiXext.h:54: error: expected '=', ',',
';', 'asm' or '__attribute__' before 'XPanoramiXQueryVersion'
/usr/include/X11/extensions/panoramiXext.h:64: error: expected '=', ',',
';', 'asm' or '__attribute__' before 'XPanoramiXGetState'
/usr/include/X11/extensions/panoramiXext.h:70: error: expected '=', ',',
';', 'asm' or '__attribute__' before 'XPanoramiXGetScreenCount'
/usr/include/X11/extensions/panoramiXext.h:76: error: expected '=', ',',
';', 'asm' or '__attribute__' before 'XPanoramiXGetScreenSize'
dispatch.c: In function 'ProcCloseFont':
dispatch.c:1117: warning: 'SecurityLookupIDByType' is deprecated
(declared at ../include/resource.h:268)
make[2]: Leaving directory `/usr/src/xorg-server-1.6.5/dix'
make[2]: *** [dispatch.lo] Error 1
make[1]: Leaving directory `/usr/src/xorg-server-1.6.5/dix'
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

$ gaze from /usr/include/X11/extensions/panoramiXext.h
libxinerama-1.1:/usr/include/X11/extensions/panoramiXext.h
xineramaproto-1.1.2:/usr/include/X11/extensions/panoramiXext.h

$ gaze version libxinerama xineramaproto
Grimoire  Section     Spell          Grimoire Version  Installed Version
--------  -------     -----          ----------------  -----------------
test      xorg-lib    libxinerama    1.1               1.1
test      xorg-proto  xineramaproto  1.2               1.2